version: '3.8'

services:
  bmstupresstopdf:
    image: node:22
    container_name: bmstuPressToPDF
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        apt-get update && apt-get update &&
        apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 xdg-utils chromium &&
        npm install &&
        npx tsc &&
        node ./dist/bmstuPressBot.js
      "
